services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_kotlin_local
    ports:
      - "5432:5432"
    volumes:
      - todo_kotlin_data:/var/lib/postgresql/data
volumes:
  todo_kotlin_data:
